version: "3.8"

services:
#------------------------------------------applicazione maoneytracker
  app: 
    build: .
    container_name: moneytracker
    restart: unless-stopped
    ports:
      - 8081:8081
      #- 9443:9443
    depends_on:
      db:
        condition: service_healthy
      vault:
        condition: service_healthy
    networks:
      - local-app
#------------------------------------------database business logic
  db:
    build: ./docker/sql
    container_name: mt_database
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_DATABASE=ssd_app
      - MYSQL_USER=user
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
    healthcheck:
      test: "exit 0"
    networks:
      - local-app
#------------------------------------------database keycloak
  postgres: 
    image: postgres:13.2
    container_name: kc_database
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    networks:
      - local-keycloak
#------------------------------------------istanza keycloak
  keycloak:
    image: jboss/keycloak:15.0.2
    container_name: mt_keycloak
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      #KEYCLOAK_FRONTEND_URL: http://localhost/auth
    networks:
      - local-keycloak
      - local-app
#------------------------------------------vault
  vault:
    image: vault
    container_name: mt_vault
    ports:
      - "8200:8200"
    restart: always
    volumes:
      - ./docker/vault/volumes/logs:/vault/logs
      - ./docker/vault/volumes/file:/vault/file
      - ./docker/vault/volumes/config:/vault/config
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config=/vault/config/vault.json
    healthcheck:
      test: ["CMD", "curl http://vault:8200/v1/sys/health || exit 0"]
      interval: 30s
      timeout: 5s
      retries: 15
      start_period: 10s
    networks:
      - local-app
#------------------------------------------nginx
  proxy:
    image: nginx:1.17.10
    depends_on:
      - app
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - local-app
#------------------------------------------networks
networks:
  local-keycloak: #connessione kc-postges
  local-app: #connessione app-keycloak-vault-db